# SPDX-License-Identifier: MIT
name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and run tests (rust ${{ matrix.rust }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install linux-modules-extra-$(uname -r)
        uses: tecolicom/actions-use-apt-tools@main
        with:
          tools: linux-modules-extra-$(uname -r)
      - name: Insert required modules
        run: |
          sudo depmod
          sudo modprobe -v zram
          sudo modprobe -v zstd
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install toolchain
        run: | 
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - name: Build
        run: make program CARGOFLAGS="--verbose"
      - name: Run tests
        run: make check CARGOFLAGS="--verbose"
      - name: Check program invocation
        run: tests/test-invocations.sh target/release/zram-generator

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install toolchain
        run: |
          rustup toolchain install stable
          rustup default stable
      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install toolchain
        run: | 
          rustup toolchain install nightly
          rustup default nightly
      - name: Validate clippy
        run: make clippy CARGOFLAGS="-- -D warnings"
